---
- hosts: all
  gather_facts: no
  remote_user: ansadmin
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t swapie123/mavenwebapp .
...
