---
- hosts: all
  gather_facts: no
  remote_user: ansadmin
  tasks:
    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
        src: target
        dest: /home/ansadmin
    - name: Build image
      command: docker build -t swapie123/mavenwebapp .
    - name: docker login
      command: docker login -u swapie123 -p Nishi5432!
    - name: docker image push
      command: docker push swapie123/mavenwebapp
    - name: docker run container
      command: docker run -d -p 9090:9090 swapie123/mavenwebapp
...
