---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t swapie123/mavenwebapp .
...
