- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build image
      command: docker build -t swapie123/mavenwebapp .
    - name: docker login
      command: docker login -u swapie123 -p Nishi5432!
    - name: docker image push
      command: docker push swapie123/mavenwebapp
    - name: docker run container
      command: docker run -d -p 8081:8080 swapie123/mavenwebapp
